site_name: !ENV [SITE_NAME, 'yaba']
site_author: Oleg Larkin
site_url: http://yaba.su/

theme:
  name: null
  custom_dir: 'light_theme/'
  navigation_depth: 3
  locale: ru

plugins:
  - search:
      lang:
        - ru
        - en
  - macros

nav:
  - Домой: 'index.md'
  - Жизнь:
    - Дом Совы на Тихой: life/priozersk/dom-sovi.md
    - Великий Новгород: life/velikiy-novgorod/index.md
    - Выборг: life/viborg/index.md
  - Habr:
    - Обвиваем YouTube змеем, или как смотреть и скачивать видео с YouTube без VPN на чистом Python-е. Часть 1: habr/anti-dpi.md
  # - JS:
  #   - Счастливый билетик:
  #     - js/lucky_ticket/index.md
  #     - js/lucky_ticket/basic_solution.md
  #     - js/lucky_ticket/tasks_separation.md
  #     - js/lucky_ticket/sixty-fps.md

repo_name: GitHub
repo_url: https://github.com/ollar/yaba

markdown_extensions:
  - footnotes
  - abbr
  - def_list
  - nl2br

hooks:
  - my_hooks.py
