site_name: !ENV [SITE_NAME, 'yaba']
site_author: Oleg Larkin
site_url: http://yaba.su/

theme:
  name: null
  custom_dir: 'light_theme/'
  navigation_depth: 3
  locale: ru

plugins:
  - search:
      lang:
        - ru
        - en

nav:
  - Домой: 'index.md'
  - JS:
    - Счастливый билетик:
      - js/lucky_ticket/index.md
      - js/lucky_ticket/basic_solution.md
      - js/lucky_ticket/tasks_separation.md

repo_name: GitHub
repo_url: https://github.com/ollar/yaba

markdown_extensions:
  - footnotes
  - abbr
  - def_list
  - nl2br
