site_name: !ENV [SITE_NAME, 'yaba']

theme:
  name: null
  custom_dir: 'light_theme/'
  navigation_depth: 3

plugins:
  - search:
      lang:
        - ru
        - en

repo_name: Github
repo_url: https://github.com/ollar/yaba
