site_name: !ENV [SITE_NAME, 'yaba']

theme:
  name: null
  custom_dir: 'light_theme/'
  navigation_depth: 3
  locale: ru

plugins:
  - search:
      lang:
        - ru
        - en

repo_name: GitHub
repo_url: https://github.com/ollar/yaba
# edit_uri: docs

markdown_extensions:
  - footnotes
  - abbr
  - def_list
